### ISSUE TITLE
Some questions about caption annotation of 1st half.

### ISSUE THREAD

**Issue by starvinlw** [SoccerNet/sn-caption#1]
why does the caption annotation begin from 10:00 for the 1st half but 00:00 for the 2nd half?

**Comment by Hmkhalla** [comment]
Hi @starvinlw,
The captions do not necessarily begin at 00:00. Concerning the 2nd half, the time in the labels is not the one of the match but from the video itself. So 10:00 means 10:00 of the video. Does this answer to your question?
