### ISSUE TITLE
Can't download the dataset

### ISSUE THREAD

**Issue by Youngphone** [SoccerNet/sn-caption#3]
`from SoccerNet.Downloader import SoccerNetDownloader as SNdl`
`mySNdl = SNdl(LocalDirectory="path/to/SoccerNet")`
`mySNdl.downloadDataTask(task="caption-2023", split=["train","valid", "test","challenge"])`
When use the API to downlaod the data, I get HTTP Error 503: Service Unavailable.

**Comment by SilvioGiancola** [comment]
We are experiencing some connection issues at our university, please bear with us.

**Comment by SilvioGiancola** [comment]
Our server is back online. Please give it a try now.
