### ISSUE TITLE
Download dataset

### ISSUE THREAD

**Issue by HangFang6** [SoccerNet/sn-caption#4]
Looking forward to your reply, but I encountered some difficulties downloading the dataset with a password: How can this be solved?
![image](https://github.com/SoccerNet/sn-caption/assets/87681879/fd8d16d5-d76f-4c63-9733-88a1e4ceb2f7)

**Comment by SilvioGiancola** [comment]
This work on my side: https://github.com/SoccerNet/sn-caption?tab=readme-ov-file#how-to-download-the-dataset

```
from SoccerNet.Downloader import SoccerNetDownloader as SNdl
mySNdl = SNdl(LocalDirectory="path/to/SoccerNet")
mySNdl.downloadDataTask(task="caption-2023", split=["train","valid", "test","challenge"]) # 2023 challenge
mySNdl.downloadDataTask(task="caption-2024", split=["train","valid", "test","challenge"]) # 2024 challenge
```

I am not sure what your script does exactly?

**Comment by bread-555** [comment]
I also have this problem. specifically, when I download the "video.ini" file 
<img width="691" alt="截屏2024-04-21 02 51 57" src="https://github.com/SoccerNet/sn-caption/assets/88585410/c9c677b8-7047-447d-9697-9f8f3803c8d8">

**Comment by SilvioGiancola** [comment]
For the captioning task, please use the recommended line of codes:
```
from SoccerNet.Downloader import SoccerNetDownloader as SNdl
mySNdl = SNdl(LocalDirectory="path/to/SoccerNet")
mySNdl.downloadDataTask(task="caption-2023", split=["train","valid", "test","challenge"]) # 2023 challenge
mySNdl.downloadDataTask(task="caption-2024", split=["train","valid", "test","challenge"]) # 2024 challenge
```
